import Moment from 'moment'
export const visitorDetailEmpty = {
    addlCol1: null,
    addlCol2: null,
    addlCol3: null,
    addlCol4: null,
    addlCol5: null,
    email: "",
    fullName: "",
    mobile: "",
    address: null,
    company: "",
    designation: null,
    idProof: null,
    orgId: null,
    photoProof: null,
    visitorId: null,
    checkInTime: null,
    checkOutTime: null,
    date: Moment().format("DD-MM-YYYY"),
    department: null,
    inTime: Moment().format('HH:mm:ss'),
    inviteCode: null,
    outTime: null,
    purpose: null,
    remarks: null,
    status: null,
    userId: null,
    whomToMeet: null,
    whomToMeetName: null,
    visitorList: null,
    inOutId: null,
    rescheduleInTime: null,
    rescheduleOutTime: null,
    imageBase64StringPhotoProof: null,
    imageBase64StringIdProof: null,
    isVip: false,
    isVizArogyaSetu: null,
    vizTemp: null,
}
export const randomColor = [
    '#E57373',
    '#EF5350',
    '#E53935',
    '#D32F2F',
    '#C62828',
    '#B71C1C',
    '#FF8A80',
    '#FF5252',
    '#FF1744',
    '#D50000',
    '#FBC02D',
    '#F9A825',
    '#F57F17',
    '#FFC107',
    '#FFB300',
    '#FFA000',
    '#FF8F00',
    '#FF6F00',
    '#FFA726',
    '#FF9800',
    '#FB8C00',
    '#F57C00',
    '#EF6C00',
    '#E65100',
    '#FFAB40',
    '#FF9100',
    '#FF6D00',
    '#FF7043',
    '#FF5722',
    '#F4511E',
    '#E64A19',
    '#D84315',
    '#BF360C',
    '#FF6E40',
    '#FF3D00',
    '#DD2C00',
    '#A1887F',
    '#8D6E63',
    '#795548',
    '#6D4C41',
    '#5D4037',
    '#4E342E',
    '#3E2723',
    '#757575',
    '#616161',
    '#424242',
    '#212121',
    '#90A4AE',
    '#78909C',
    '#607D8B',
    '#546E7A',
    '#455A64',
    '#37474F',
    '#263238',
]
// export const visitorDetailEmpty = {
//    "addlCol1":"",
//    "addlCol2":"",
//    "addlCol3":"",
//    "addlCol4":"",
//    "addlCol5":"",
//    "address":"",
//    "allSettings":null,
//    "checkInTime":"",
//    "checkOutTime":"",
//    "colName1":"",
//    "colName2":"",
//    "colName3":"",
//    "colName4":"",
//    "colName5":"",
//    "compAddress":"",
//    "company":"",
//    "compname":"",
//    "date":Moment().format("DD-MM-YYYY"),
//    "department":"",
//    "designation":"",
//    "email":"",
//    "fullName":"",
//    "idProof":"",
//    "imageBase64StringIdProof":null,
//    "imageBase64StringPhotoProof":null,
//    "inOutId":null,
//    "inTime":Moment().format('HH:mm:ss'),
//    "inviteCheckin":null,
//    "inviteCode":null,
//    "isArogyaSettng":null,
//    "isTempreutr":null,
//    "isVip":false,
//    "isVizArogyaSetu":null,
//    "meetInTime":null,
//    "meetOutTime":null,
//    "mobile":"",
//    "orgId":null,
//    "outTime":null,
//    "photoProof":null,
//    "print":null,
//    "purpose":"",
//    "remarks":"",
//    "rescheduleInTime":null,
//    "rescheduleOutTime":null,
//    "status":null,
//    "userId":null,
//    "visitorId":null,
//    "visitorList":null,
//    "vizTemp":"",
//    "whomToMeet":null,
//    "whomToMeetName":null,
//    "whoomToMeetList":null
// }
export const AllSettingEmpty = {
    "mappingVM": {
        "mappID": 0,
        "col1": "string",
        "col2": "string",
        "col3": "string",
        "col4": "string",
        "col5": "string",
        "valCol1": 0,
        "valCol2": 0,
        "valCol3": 0,
        "valCol4": 0,
        "valCol5": 0,
        "userId": 0,
        "orgId": 0
    },
    "settingsVM": {
        "settingsID": 0,
        "userId": 0,
        "orgId": 0,
        "templateId": 0,
        "vAddlCol1": true,
        "vAddlCol2": true,
        "vAddlCol3": true,
        "vAddlCol4": true,
        "vAddlCol5": true,
        "vAddress": true,
        "vCompany": true,
        "vDesignation": true,
        "vEmail": true,
        "vFullName": true,
        "vIdProof": true,
        "vMobile": true,
        "vPhotoProof": true,
        "vDepartment": true,
        "vPurpose": true,
        "vArogya": true,
        "vtemprature": true
    },
    "emailConfigurationVM": {
        "id": 0,
        "userId": 0,
        "portName": 0,
        "emailId": "string",
        "mailPassword": "string",
        "hostName": "string",
        "isSsl": true
    },
    "addlCol1": "string",
    "addlCol2": "string",
    "addlCol3": "string",
    "addlCol4": "string",
    "addlCol5": "string"
}